### ISSUE TITLE
Align RNA-seq time series data (Apul)

### ISSUE THREAD

**Issue by sr320** [urol-e5/timeseries_molecular#1]
Take time series data that is from A pulcra and align to "new" genome using Hisat.

Genome: https://gannet.fish.washington.edu/seashell/bu-github/deep-dive-expression/D-Apul/data/Apulcra-genome.fa https://gannet.fish.washington.edu/seashell/bu-github/deep-dive-expression/D-Apul/data/Apulcra-genome.fa.fai

Gff: https://gannet.fish.washington.edu/seashell/bu-github/deep-dive-expression/D-Apul/data/Apulcra-genome.gff

**Comment by sr320** [comment]
note A pulcra is ACR  in  https://github.com/urol-e5/timeseries_molecular/blob/main/data/rna_metadata.csv

**Comment by kubu4** [comment]
Which repo should code go in? `deep-dive-expression` or `timeseries_molecular`?

**Comment by sr320** [comment]
`timeseries_molecular` - the repo this issue is in - thanks!

**Comment by kubu4** [comment]
Also, is this repo going to be multi-species, like `deep-dive`? I'm asking so that we can get things organized before we start adding too many files to the existing directory structure.

**Comment by sr320** [comment]
yes will be multi species.

**Comment by kubu4** [comment]
Alignments complete.


Full output from alignments (excluding BAMS) is here:

https://github.com/urol-e5/timeseries_molecular/tree/main/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2

Will be adding/updating README later today.

There's a subdirectory for each sample, containing individual alignments and alignment info, as well as Ballgown-formatted table files.

MultiQC alignment report (GitHub):

https://github.com/urol-e5/timeseries_molecular/blob/main/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2/multiqc_report.html

DESeq2 count matrices (raw):

- [apul-gene_count_matrix.csv](https://raw.githubusercontent.com/urol-e5/timeseries_molecular/refs/heads/main/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2/apul-gene_count_matrix.csv)

- [apul-transcript_count_matrix.csv](https://github.com/urol-e5/timeseries_molecular/raw/refs/heads/main/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2/apul-transcript_count_matrix.csv)

StringTie GTF (raw):

[Apulchra-genome.stringtie.gtf](https://github.com/urol-e5/timeseries_molecular/raw/refs/heads/main/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2/Apulchra-genome.stringtie.gtf)

Currently `rsync-ing` repo to have access to BAMS. Will report back when that's complete.

**Comment by kubu4** [comment]
`rsync`-ing complete.

_All_ files available here:

https://gannet.fish.washington.edu/Atumefaciens/gitrepos/urol-e5/timeseries_molecular/D-Apul/output/02.20-D-Apul-RNAseq-alignment-HiSat2/
