### ISSUE TITLE
Ordering for lipidomics / metabolomics sample processing 

### ISSUE THREAD

**Issue by JillAshey** [urol-e5/timeseries_molecular#4]
We need to order the following for lipidomics / metabolomics sample processing:

- [1.5 mL tubes](https://www.amazon.com/Microcentrifuge-Sterilized-Plastic-Storage-Without/dp/B09FJFB6PM/ref=sr_1_3?crid=13DSTTNR2MVGV&dib=eyJ2IjoiMSJ9.1Ve7Zo-_T9UJE67U1IjHwx4sA5JDWDkuHivo5_7WDyQsZnpbO4l3RfGOF_ddEEKOdWUps1Yo8hAw3Apd85wyjq-bgHwF9mLtlgn2hvcZ0Oy74FNHJTCV79OUG7okP4QDV7HsMn_0F1PeIrJd2bygAHV6amRVleKWr4TuLlEFHNGypD1CrwRuUUyrWbBjGaJHeapmnlBR2xlGoSeVPyKXMaIOinTJhMjUnusBy88rt8c.ifPG5JkOVb1Ny6c2rFLZL_NLkxjr4_5rT4nh62iaCR0&dib_tag=se&keywords=1.5mL%2Btubes%2Bsterile&qid=1731006440&sprefix=1.5ml%2Btubes%2Bsteril%2Caps%2C101&sr=8-3&th=1)
- [Plastic pestles](https://www.fishersci.com/shop/products/micropestle-w-1-5ml-tube-100cs/50212457)
- [LCMS grade water](https://www.fishersci.com/shop/products/water-optima-lc-ms-grade-fisher-chemical/W6212)

Feel free to order from wherever, the links are just suggestions. Ideally, materials would arrive ASAP. 

Please send to: 
Jill Ashey 
Center for Biotechnology and Life Sciences
120 Flagg Road
Kingston, RI 02881
If phone or email is needed: 9083297026 or jillashey@uri.edu. 

#### Important links

- [Sample list](https://docs.google.com/spreadsheets/d/1iFsVfp1vix9IfNcqSajQfLgXXDg0CCPT/edit?gid=374085219#gid=374085219)
- [Draft protocol](https://docs.google.com/document/d/1EiO1sB_tROCc0xWuQr3LXpvTtNoSSY8oLlTLwOQC1eo/edit?tab=t.0)

**Comment by JillAshey** [comment]
@AHuffmyer anything else you can think of?

**Comment by sr320** [comment]
@AHuffmyer
<https://urldefense.com/v3/__https://github.com/AHuffmyer__;!!K-Hz7m0Vt54!j3ehgB7vo2v8ytporJhyMQ0UlAuZnUM-SkLRO6quRderLz4CaX4Bk8EqkCdVdfmUmuDrDd-_2YRs1mA9wSEJQXI$>
can
you place this order?

**Comment by AHuffmyer** [comment]
@JillAshey can you confirm the quantities? 

1.5 mL tubes = 500 
Pestles = 100
Water = 2.5L

**Comment by JillAshey** [comment]
@AHuffmyer correct!

**Comment by AHuffmyer** [comment]
Submitted TREQ005634, added to purchasing log
