### ISSUE TITLE
Evaluate and respond to Azenta 30-1067895835 WBGS QC report

### ISSUE THREAD

**Issue by kubu4** [urol-e5/timeseries_molecular#5]
Email from Azenta today:

> Hi Samuel,
>
> An update for your current order is now available:
>
>Service Line: Next Generation Sequencing
Order Type: Whole Genome Methylation
Order Number: 30-1067895835
Order Name: e5-coral-120-wgbs-time-series
PO Number: PO-0100094285
Project Status: Sample QC, Processing
Comments: I am letting you know that DNA sample QC has been completed for your project. Please review the attached results summary pdf. Please note, some samples are below 100ng of DNA per Qubit (marked with QC note 1), which is our suggested minimum for this type of library prep. Please let me know how you would like to proceed:
>1. Continue with all samples further as is, acknowledging that the likelihood of successful library preparation is reduced, and we may not yield sufficient library for sequencing.
>2. Resubmit the samples.
>3. Omit the samples from library prep.
>
> Also note, our RNA spot check showed greater than 10% RNA in most samples tested. We would suggest RNase treatment for all samples, as any RNA in the libraries could have negative effects on the data. We could perform RNase treatments in house, at $53/sample, and 2-3 days of added project turnaround time.
>
>Please let me know if you would like this option, and I will happily adjust your quote accordingly. If you have any questions, please do not hesitate to reach out. Upon your reply I will follow up accordingly with next steps. I look forward to hearing from you.

[Sample QC report of_30-1067895835_241111101420.pdf](https://github.com/user-attachments/files/17782227/Sample.QC.report.of_30-1067895835_241111101420.pdf)

Pinging @JillAshey, as she's been the lead on this.

**Comment by sr320** [comment]
@hputnam @JillAshey - I say we go with 
> Continue with all samples further as is, acknowledging that the likelihood of successful library preparation is reduced, and we may not yield sufficient library for sequencing.

Does this seem reasonable?

**Comment by JillAshey** [comment]
Agreed!

**Comment by sr320** [comment]
@kubu4 you can tell them to move forward with option 1

**Comment by kubu4** [comment]
Done.
